name: My First Workflow
on:
  push:
    branches:
      - main
jobs:
  first_job:
    name: My first job
    runs-on: ubuntu-latest
    steps:
      - run: | 
          echo "Hello ${{ env.WHO_TO_GREET }} from ${{ github.actor }}."
          echo "My secret is ${{ secrets.MY_SECRET }}."
